### ISSUE TITLE
Unable to create new EAB if `data.type: memory`

### ISSUE THREAD

**Issue by seriy379** [PeculiarVentures/acme-ts#31]
```
[error] 2022-05-14T08:59:49.476Z PVAcmeController: Element already exists {
  stack: 'Error: Element already exists\n' +
    '    at ExternalAccountRepository.add (/app/node_modules/@peculiar/acme-data-memory/build/cjs/repositories/base.js:22:19)\n' +
    '    at PVExternalAccountService.create (/app/node_modules/@peculiar/acme-server/build/cjs/services/external_account.js:20:64)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:95:5)'
}
```

for `data.type: dynamo` everything works fine

**Comment by microshine** [comment]
```
Successfully published:
 - @peculiar/acme-data-memory@1.7.3
```
